#!/usr/bin/env bash
# Check for the number of arguments passed
if [ $# -lt 4 ] 
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# Extract arguments
	file_path="$1"
	server_ip="$2"
	username="$3"
	key_path="$4"
	# Disable strict host key checking
	scp -o StrictHostKeyChecking=no -i "$key_path" "$file_path" $username@$server_ip:~
fi
