#!/usr/bin/env bash
# Start Apache
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install apache2
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo service  apache2 restart
